name: CI - Docker Multi-Stage Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Create a lowercase version of the repo name for Docker tags
      - name: Prepare lowercase repo name
        id: prep
        run: |
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      # 🧱 Build and push using multi-stage Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ env.repo_name }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ env.repo_name }}:${{ github.sha }}
